name: Python
on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install audio dependencies
        run: |
          sudo apt install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0 ffmpeg

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Running the python code
        run: |
          python ./src/main.py
